name: Publish to npm
on:
    release:
        types: [created]
jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
        steps:
            - name: Checkout
              uses: actions/checkout@v5
            - name: Setup Node
              uses: actions/setup-node@v5
              with:
                  node-version: '20.x'
                  registry-url: 'https://registry.npmjs.org'
            - name: Install dependencies
              run: npm ci
            - name: Prerelease
              run: npm run prerelease
            - name: Publish package
              run: npm publish --provenance
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
